[package]
name = "nettrap-proto-raw"
description = "Raw protocol handler for NetTrap"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
nettrap-core.workspace = true
nettrap-fsutil.workspace = true
tracing.workspace = true
base64.workspace = true
