[package]
name = "nettrap-api"
description = "API for NetTrap"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
nettrap-core.workspace = true
nettrap-flow.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
parking_lot.workspace = true
tokio.workspace = true
axum = "0.8.9"
tower = "0.5"
tracing.workspace = true
