[package]
name = "nettrap-tui"
description = "TUI for NetTrap"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
nettrap-core.workspace = true
thiserror.workspace = true
ratatui = "0.30"
crossterm = "0.29"
