[package]
name = "nettrap-cli"
description = "CLI for NetTrap"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "nettrap"
path = "src/main.rs"

[dependencies]
nettrap-core.workspace = true
nettrap-flow.workspace = true
nettrap-events.workspace = true
nettrap-policy.workspace = true
nettrap-attribution.workspace = true
nettrap-interceptor.workspace = true
nettrap-socket.workspace = true
nettrap-proto-dns.workspace = true
nettrap-proto-http.workspace = true
nettrap-proto-tls.workspace = true
nettrap-proto-smtp.workspace = true
nettrap-proto-ftp.workspace = true
nettrap-proto-raw.workspace = true
nettrap-proto-pop3.workspace = true
nettrap-proto-irc.workspace = true
nettrap-proto-tftp.workspace = true
nettrap-proto-telnet.workspace = true
nettrap-proto-ssh.workspace = true
nettrap-proto-smb.workspace = true
nettrap-proto-rdp.workspace = true
nettrap-proto-redis.workspace = true
nettrap-proto-mysql.workspace = true
nettrap-proto-ldap.workspace = true
nettrap-proto-mqtt.workspace = true
nettrap-proto-snmp.workspace = true
nettrap-proto-socks.workspace = true
nettrap-proto-memcached.workspace = true
nettrap-proto-nkn.workspace = true
nettrap-proto-postgres.workspace = true
nettrap-proto-sip.workspace = true
nettrap-proto-upnp.workspace = true
nettrap-proto-ntp.workspace = true
nettrap-proto-coap.workspace = true
nettrap-tls-mitm.workspace = true
nettrap-proxy.workspace = true
nettrap-pcap.workspace = true
nettrap-report.workspace = true
nettrap-storage.workspace = true
thiserror.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
clap.workspace = true
config.workspace = true
directories.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tokio.workspace = true
chrono.workspace = true
uuid.workspace = true
base64.workspace = true
bytes.workspace = true
parking_lot.workspace = true
hostname.workspace = true
rand.workspace = true
regex.workspace = true
reqwest.workspace = true
async-trait.workspace = true
rusqlite.workspace = true
sqlx.workspace = true
which.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.60", features = ["Win32_System_LibraryLoader"] }
