[package]
name = "nettrap-proto-ftp"
description = "FTP protocol handler for NetTrap"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
nettrap-core.workspace = true
thiserror.workspace = true
serde.workspace = true
bytes.workspace = true
chrono.workspace = true
tracing.workspace = true
memchr.workspace = true
hostname.workspace = true
libc.workspace = true
