[package]
name = "nettrap-events"
description = "Event system for NetTrap"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
nettrap-core.workspace = true
nettrap-flow.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
bytes.workspace = true
uuid.workspace = true
chrono.workspace = true
crossbeam.workspace = true
parking_lot.workspace = true
hashbrown.workspace = true
tracing.workspace = true
tokio.workspace = true
async-trait.workspace = true