//! Auto-generated translation data table for NetTrap reports.
//!
//! This is a static data file (~30+ languages x ~30 keys). Not a "God Object":
//! it is a compile-time resource bundle accessed via [`super::t`].

use std::collections::HashMap;
use std::sync::LazyLock;

pub(crate) static TRANSLATIONS: LazyLock<
    HashMap<&'static str, HashMap<&'static str, &'static str>>,
> = LazyLock::new(|| {
    let mut m = HashMap::new();

    let mut en = HashMap::new();
    en.insert(
        "report_title",
        "NetTrap - Network Behavior Indicators Report",
    );
    en.insert("total_events", "Total Events");
    en.insert("unique_sources", "Unique Sources");
    en.insert("protocols", "Protocols");
    en.insert("protocol_summary", "Protocol Summary");
    en.insert("protocol", "Protocol");
    en.insert("events", "Events");
    en.insert("all_events", "All Events");
    en.insert("time", "Time");
    en.insert("listener", "Listener");
    en.insert("source", "Source");
    en.insert("destination", "Destination");
    en.insert("port", "Port");
    en.insert("indicators", "Indicators");
    en.insert("process", "Process");
    en.insert("generated_by", "Report generated by NetTrap");
    en.insert("no_events", "No events captured");
    en.insert("summary", "Summary");
    en.insert("connections", "Connections");
    en.insert("credentials_captured", "Credentials Captured");
    en.insert("files_transferred", "Files Transferred");
    en.insert("dns_queries", "DNS Queries");
    en.insert("http_requests", "HTTP Requests");
    en.insert("smtp_emails", "SMTP Emails");
    en.insert("ssh_attempts", "SSH Attempts");
    en.insert("telnet_sessions", "Telnet Sessions");
    en.insert("start_time", "Start Time");
    en.insert("end_time", "End Time");
    en.insert("duration", "Duration");
    en.insert("node_id", "Node ID");
    en.insert("region", "Region");
    m.insert("en", en);

    let mut es = HashMap::new();
    es.insert(
        "report_title",
        "NetTrap - Informe de Indicadores de Comportamiento de Red",
    );
    es.insert("total_events", "Total de Eventos");
    es.insert("unique_sources", "Fuentes Únicas");
    es.insert("protocols", "Protocolos");
    es.insert("protocol_summary", "Resumen de Protocolos");
    es.insert("protocol", "Protocolo");
    es.insert("events", "Eventos");
    es.insert("all_events", "Todos los Eventos");
    es.insert("time", "Hora");
    es.insert("listener", "Servicio");
    es.insert("source", "Origen");
    es.insert("destination", "Destino");
    es.insert("port", "Puerto");
    es.insert("indicators", "Indicadores");
    es.insert("process", "Proceso");
    es.insert("generated_by", "Informe generado por NetTrap");
    es.insert("no_events", "No se capturaron eventos");
    es.insert("summary", "Resumen");
    es.insert("connections", "Conexiones");
    es.insert("credentials_captured", "Credenciales Capturadas");
    es.insert("files_transferred", "Archivos Transferidos");
    es.insert("dns_queries", "Consultas DNS");
    es.insert("http_requests", "Peticiones HTTP");
    es.insert("smtp_emails", "Correos SMTP");
    es.insert("ssh_attempts", "Intentos SSH");
    es.insert("telnet_sessions", "Sesiones Telnet");
    es.insert("start_time", "Hora de Inicio");
    es.insert("end_time", "Hora de Fin");
    es.insert("duration", "Duración");
    es.insert("node_id", "ID de Nodo");
    es.insert("region", "Región");
    m.insert("es", es);

    let mut de = HashMap::new();
    de.insert(
        "report_title",
        "NetTrap - Netzwerkverhaltens-Indikatoren Bericht",
    );
    de.insert("total_events", "Gesamtereignisse");
    de.insert("unique_sources", "Eindeutige Quellen");
    de.insert("protocols", "Protokolle");
    de.insert("protocol_summary", "Protokollzusammenfassung");
    de.insert("protocol", "Protokoll");
    de.insert("events", "Ereignisse");
    de.insert("all_events", "Alle Ereignisse");
    de.insert("time", "Zeit");
    de.insert("listener", "Dienst");
    de.insert("source", "Quelle");
    de.insert("port", "Port");
    de.insert("indicators", "Indikatoren");
    de.insert("process", "Prozess");
    de.insert("generated_by", "Bericht erstellt von NetTrap");
    de.insert("no_events", "Keine Ereignisse erfasst");
    de.insert("summary", "Zusammenfassung");
    de.insert("connections", "Verbindungen");
    de.insert("credentials_captured", "Erfasste Anmeldedaten");
    de.insert("files_transferred", "Übertragene Dateien");
    de.insert("dns_queries", "DNS-Abfragen");
    de.insert("http_requests", "HTTP-Anfragen");
    de.insert("smtp_emails", "SMTP-E-Mails");
    de.insert("ssh_attempts", "SSH-Versuche");
    de.insert("telnet_sessions", "Telnet-Sitzungen");
    de.insert("start_time", "Startzeit");
    de.insert("end_time", "Endzeit");
    de.insert("duration", "Dauer");
    de.insert("node_id", "Knoten-ID");
    de.insert("region", "Region");
    de.insert("destination", "Ziel");
    m.insert("de", de);

    let mut fr = HashMap::new();
    fr.insert(
        "report_title",
        "NetTrap - Rapport d'Indicateurs de Comportement Réseau",
    );
    fr.insert("total_events", "Total des Événements");
    fr.insert("unique_sources", "Sources Uniques");
    fr.insert("protocols", "Protocoles");
    fr.insert("protocol_summary", "Résumé des Protocoles");
    fr.insert("protocol", "Protocole");
    fr.insert("events", "Événements");
    fr.insert("all_events", "Tous les Événements");
    fr.insert("time", "Heure");
    fr.insert("listener", "Service");
    fr.insert("source", "Source");
    fr.insert("port", "Port");
    fr.insert("indicators", "Indicateurs");
    fr.insert("process", "Processus");
    fr.insert("generated_by", "Rapport généré par NetTrap");
    fr.insert("no_events", "Aucun événement capturé");
    fr.insert("summary", "Résumé");
    fr.insert("connections", "Connexions");
    fr.insert("credentials_captured", "Identifiants Capturés");
    fr.insert("files_transferred", "Fichiers Transférés");
    fr.insert("dns_queries", "Requêtes DNS");
    fr.insert("http_requests", "Requêtes HTTP");
    fr.insert("smtp_emails", "E-mails SMTP");
    fr.insert("ssh_attempts", "Tentatives SSH");
    fr.insert("telnet_sessions", "Sessions Telnet");
    fr.insert("start_time", "Heure de Début");
    fr.insert("end_time", "Heure de Fin");
    fr.insert("duration", "Durée");
    fr.insert("node_id", "ID du Nœud");
    fr.insert("region", "Région");
    fr.insert("destination", "Destination");
    m.insert("fr", fr);

    let mut it = HashMap::new();
    it.insert(
        "report_title",
        "NetTrap - Rapporto Indicatori di Comportamento di Rete",
    );
    it.insert("total_events", "Totale Eventi");
    it.insert("unique_sources", "Sorgenti Uniche");
    it.insert("protocols", "Protocolli");
    it.insert("protocol_summary", "Riepilogo Protocolli");
    it.insert("protocol", "Protocollo");
    it.insert("events", "Eventi");
    it.insert("all_events", "Tutti gli Eventi");
    it.insert("time", "Ora");
    it.insert("listener", "Servizio");
    it.insert("source", "Sorgente");
    it.insert("port", "Porta");
    it.insert("indicators", "Indicatori");
    it.insert("process", "Processo");
    it.insert("generated_by", "Rapporto generato da NetTrap");
    it.insert("no_events", "Nessun evento catturato");
    it.insert("summary", "Riepilogo");
    it.insert("connections", "Connessioni");
    it.insert("credentials_captured", "Credenziali Catturate");
    it.insert("files_transferred", "File Trasferiti");
    it.insert("dns_queries", "Query DNS");
    it.insert("http_requests", "Richieste HTTP");
    it.insert("smtp_emails", "E-mail SMTP");
    it.insert("ssh_attempts", "Tentativi SSH");
    it.insert("telnet_sessions", "Sessioni Telnet");
    it.insert("start_time", "Ora di Inizio");
    it.insert("end_time", "Ora di Fine");
    it.insert("duration", "Durata");
    it.insert("node_id", "ID Nodo");
    it.insert("region", "Regione");
    it.insert("destination", "Destinazione");
    m.insert("it", it);

    let mut pt = HashMap::new();
    pt.insert(
        "report_title",
        "NetTrap - Relatório de Indicadores de Comportamento de Rede",
    );
    pt.insert("total_events", "Total de Eventos");
    pt.insert("unique_sources", "Fontes Únicas");
    pt.insert("protocols", "Protocolos");
    pt.insert("protocol_summary", "Resumo de Protocolos");
    pt.insert("protocol", "Protocolo");
    pt.insert("events", "Eventos");
    pt.insert("all_events", "Todos os Eventos");
    pt.insert("time", "Hora");
    pt.insert("listener", "Serviço");
    pt.insert("source", "Origem");
    pt.insert("port", "Porta");
    pt.insert("indicators", "Indicadores");
    pt.insert("process", "Processo");
    pt.insert("generated_by", "Relatório gerado pelo NetTrap");
    pt.insert("no_events", "Nenhum evento capturado");
    pt.insert("summary", "Resumo");
    pt.insert("connections", "Conexões");
    pt.insert("credentials_captured", "Credenciais Capturadas");
    pt.insert("files_transferred", "Arquivos Transferidos");
    pt.insert("dns_queries", "Consultas DNS");
    pt.insert("http_requests", "Requisições HTTP");
    pt.insert("smtp_emails", "E-mails SMTP");
    pt.insert("ssh_attempts", "Tentativas SSH");
    pt.insert("telnet_sessions", "Sessões Telnet");
    pt.insert("start_time", "Hora de Início");
    pt.insert("end_time", "Hora de Fim");
    pt.insert("duration", "Duração");
    pt.insert("node_id", "ID do Nó");
    pt.insert("region", "Região");
    pt.insert("destination", "Destino");
    m.insert("pt", pt);

    let mut nl = HashMap::new();
    nl.insert(
        "report_title",
        "NetTrap - Netwerkgedragsindicatoren Rapport",
    );
    nl.insert("total_events", "Totaal Gebeurtenissen");
    nl.insert("unique_sources", "Unieke Bronnen");
    nl.insert("protocols", "Protocollen");
    nl.insert("protocol_summary", "Protocoloverzicht");
    nl.insert("protocol", "Protocol");
    nl.insert("events", "Gebeurtenissen");
    nl.insert("all_events", "Alle Gebeurtenissen");
    nl.insert("time", "Tijd");
    nl.insert("listener", "Service");
    nl.insert("source", "Bron");
    nl.insert("port", "Poort");
    nl.insert("indicators", "Indicatoren");
    nl.insert("process", "Proces");
    nl.insert("generated_by", "Rapport gegenereerd door NetTrap");
    nl.insert("no_events", "Geen gebeurtenissen vastgelegd");
    nl.insert("summary", "Samenvatting");
    nl.insert("connections", "Verbindingen");
    nl.insert("credentials_captured", "Vastgelegde Inloggegevens");
    nl.insert("files_transferred", "Overgedragen Bestanden");
    nl.insert("dns_queries", "DNS-verzoeken");
    nl.insert("http_requests", "HTTP-verzoeken");
    nl.insert("smtp_emails", "SMTP-e-mails");
    nl.insert("ssh_attempts", "SSH-pogingen");
    nl.insert("telnet_sessions", "Telnet-sessies");
    nl.insert("start_time", "Starttijd");
    nl.insert("end_time", "Eindtijd");
    nl.insert("duration", "Duur");
    nl.insert("node_id", "Knooppunt-ID");
    nl.insert("region", "Regio");
    nl.insert("destination", "Bestemming");
    m.insert("nl", nl);

    let mut pl = HashMap::new();
    pl.insert(
        "report_title",
        "NetTrap - Raport Wskaźników Zachowań Sieciowych",
    );
    pl.insert("total_events", "Łączna Liczba Zdarzeń");
    pl.insert("unique_sources", "Unikalne Źródła");
    pl.insert("protocols", "Protokoły");
    pl.insert("protocol_summary", "Podsumowanie Protokołów");
    pl.insert("protocol", "Protokół");
    pl.insert("events", "Zdarzenia");
    pl.insert("all_events", "Wszystkie Zdarzenia");
    pl.insert("time", "Czas");
    pl.insert("listener", "Usługa");
    pl.insert("source", "Źródło");
    pl.insert("port", "Port");
    pl.insert("indicators", "Wskaźniki");
    pl.insert("process", "Proces");
    pl.insert("generated_by", "Raport wygenerowany przez NetTrap");
    pl.insert("no_events", "Nie przechwycono zdarzeń");
    pl.insert("summary", "Podsumowanie");
    pl.insert("connections", "Połączenia");
    pl.insert("credentials_captured", "Przechwycone Dane Logowania");
    pl.insert("files_transferred", "Przesłane Pliki");
    pl.insert("dns_queries", "Zapytania DNS");
    pl.insert("http_requests", "Żądania HTTP");
    pl.insert("smtp_emails", "Wiadomości SMTP");
    pl.insert("ssh_attempts", "Próby SSH");
    pl.insert("telnet_sessions", "Sesje Telnet");
    pl.insert("start_time", "Czas Rozpoczęcia");
    pl.insert("end_time", "Czas Zakończenia");
    pl.insert("duration", "Czas Trwania");
    pl.insert("node_id", "ID Węzła");
    pl.insert("region", "Region");
    pl.insert("destination", "Cel");
    m.insert("pl", pl);

    let mut ro = HashMap::new();
    ro.insert(
        "report_title",
        "NetTrap - Raport Indicatori de Comportament al Rețelei",
    );
    ro.insert("total_events", "Total Evenimente");
    ro.insert("unique_sources", "Surse Unice");
    ro.insert("protocols", "Protocoale");
    ro.insert("protocol_summary", "Rezumat Protocoale");
    ro.insert("protocol", "Protocol");
    ro.insert("events", "Evenimente");
    ro.insert("all_events", "Toate Evenimentele");
    ro.insert("time", "Ora");
    ro.insert("listener", "Serviciu");
    ro.insert("source", "Sursă");
    ro.insert("port", "Port");
    ro.insert("indicators", "Indicatori");
    ro.insert("process", "Proces");
    ro.insert("generated_by", "Raport generat de NetTrap");
    ro.insert("no_events", "Niciun eveniment capturat");
    ro.insert("summary", "Rezumat");
    ro.insert("connections", "Conexiuni");
    ro.insert("credentials_captured", "Credențiale Capturate");
    ro.insert("files_transferred", "Fișiere Transferate");
    ro.insert("dns_queries", "Interogări DNS");
    ro.insert("http_requests", "Cereri HTTP");
    ro.insert("smtp_emails", "E-mailuri SMTP");
    ro.insert("ssh_attempts", "Încercări SSH");
    ro.insert("telnet_sessions", "Sesiuni Telnet");
    ro.insert("start_time", "Ora de Început");
    ro.insert("end_time", "Ora de Sfârșit");
    ro.insert("duration", "Durată");
    ro.insert("node_id", "ID Nod");
    ro.insert("region", "Regiune");
    ro.insert("destination", "Destinație");
    m.insert("ro", ro);

    let mut sv = HashMap::new();
    sv.insert(
        "report_title",
        "NetTrap - Rapport över Nätverksbeteendeindikatorer",
    );
    sv.insert("total_events", "Totalt Antal Händelser");
    sv.insert("unique_sources", "Unika Källor");
    sv.insert("protocols", "Protokoll");
    sv.insert("protocol_summary", "Protokollsammanfattning");
    sv.insert("protocol", "Protokoll");
    sv.insert("events", "Händelser");
    sv.insert("all_events", "Alla Händelser");
    sv.insert("time", "Tid");
    sv.insert("listener", "Tjänst");
    sv.insert("source", "Källa");
    sv.insert("port", "Port");
    sv.insert("indicators", "Indikatorer");
    sv.insert("process", "Process");
    sv.insert("generated_by", "Rapport genererad av NetTrap");
    sv.insert("no_events", "Inga händelser fångade");
    sv.insert("summary", "Sammanfattning");
    sv.insert("connections", "Anslutningar");
    sv.insert("credentials_captured", "Fångade Inloggningsuppgifter");
    sv.insert("files_transferred", "Överförda Filer");
    sv.insert("dns_queries", "DNS-förfrågningar");
    sv.insert("http_requests", "HTTP-förfrågningar");
    sv.insert("smtp_emails", "SMTP-e-post");
    sv.insert("ssh_attempts", "SSH-försök");
    sv.insert("telnet_sessions", "Telnet-sessioner");
    sv.insert("start_time", "Starttid");
    sv.insert("end_time", "Sluttid");
    sv.insert("duration", "Varaktighet");
    sv.insert("node_id", "Nod-ID");
    sv.insert("region", "Region");
    sv.insert("destination", "Destination");
    m.insert("sv", sv);

    let mut da = HashMap::new();
    da.insert(
        "report_title",
        "NetTrap - Rapport over Netværksadfærdsindikatorer",
    );
    da.insert("total_events", "Samlede Hændelser");
    da.insert("unique_sources", "Unikke Kilder");
    da.insert("protocols", "Protokoller");
    da.insert("protocol_summary", "Protokolresumé");
    da.insert("protocol", "Protokol");
    da.insert("events", "Hændelser");
    da.insert("all_events", "Alle Hændelser");
    da.insert("time", "Tid");
    da.insert("listener", "Tjeneste");
    da.insert("source", "Kilde");
    da.insert("port", "Port");
    da.insert("indicators", "Indikatorer");
    da.insert("process", "Proces");
    da.insert("generated_by", "Rapport genereret af NetTrap");
    da.insert("no_events", "Ingen hændelser fanget");
    da.insert("summary", "Resumé");
    da.insert("connections", "Forbindelser");
    da.insert("credentials_captured", "Fangede Legitimationsoplysninger");
    da.insert("files_transferred", "Overførte Filer");
    da.insert("dns_queries", "DNS-forespørgsler");
    da.insert("http_requests", "HTTP-anmodninger");
    da.insert("smtp_emails", "SMTP-e-mails");
    da.insert("ssh_attempts", "SSH-forsøg");
    da.insert("telnet_sessions", "Telnet-sessioner");
    da.insert("start_time", "Starttidspunkt");
    da.insert("end_time", "Sluttidspunkt");
    da.insert("duration", "Varighed");
    da.insert("node_id", "Node-ID");
    da.insert("region", "Region");
    da.insert("destination", "Destination");
    m.insert("da", da);

    let mut fi = HashMap::new();
    fi.insert(
        "report_title",
        "NetTrap - Verkkokäyttäytymisindikaattoriraportti",
    );
    fi.insert("total_events", "Tapahtumat Yhteensä");
    fi.insert("unique_sources", "Yksilölliset Lähteet");
    fi.insert("protocols", "Protokollat");
    fi.insert("protocol_summary", "Protokollayhteenveto");
    fi.insert("protocol", "Protokolla");
    fi.insert("events", "Tapahtumat");
    fi.insert("all_events", "Kaikki Tapahtumat");
    fi.insert("time", "Aika");
    fi.insert("listener", "Palvelu");
    fi.insert("source", "Lähde");
    fi.insert("port", "Portti");
    fi.insert("indicators", "Indikaattorit");
    fi.insert("process", "Prosessi");
    fi.insert("generated_by", "Raportin loi NetTrap");
    fi.insert("no_events", "Ei kaapattuja tapahtumia");
    fi.insert("summary", "Yhteenveto");
    fi.insert("connections", "Yhteydet");
    fi.insert("credentials_captured", "Kaapatut Tunnistetiedot");
    fi.insert("files_transferred", "Siirretyt Tiedostot");
    fi.insert("dns_queries", "DNS-kyselyt");
    fi.insert("http_requests", "HTTP-pyynnöt");
    fi.insert("smtp_emails", "SMTP-sähköpostit");
    fi.insert("ssh_attempts", "SSH-yritykset");
    fi.insert("telnet_sessions", "Telnet-istunnot");
    fi.insert("start_time", "Alkamisaika");
    fi.insert("end_time", "Päättymisaika");
    fi.insert("duration", "Kesto");
    fi.insert("node_id", "Solmu-ID");
    fi.insert("region", "Alue");
    fi.insert("destination", "Kohde");
    m.insert("fi", fi);

    let mut el = HashMap::new();
    el.insert(
        "report_title",
        "NetTrap - Αναφορά Δεικτών Συμπεριφοράς Δικτύου",
    );
    el.insert("total_events", "Συνολικά Συμβάντα");
    el.insert("unique_sources", "Μοναδικές Πηγές");
    el.insert("protocols", "Πρωτόκολλα");
    el.insert("protocol_summary", "Σύνοψη Πρωτοκόλλων");
    el.insert("protocol", "Πρωτόκολλο");
    el.insert("events", "Συμβάντα");
    el.insert("all_events", "Όλα τα Συμβάντα");
    el.insert("time", "Ώρα");
    el.insert("listener", "Υπηρεσία");
    el.insert("source", "Πηγή");
    el.insert("port", "Θύρα");
    el.insert("indicators", "Δείκτες");
    el.insert("process", "Διεργασία");
    el.insert("generated_by", "Αναφορά δημιουργήθηκε από το NetTrap");
    el.insert("no_events", "Δεν καταγράφηκαν συμβάντα");
    el.insert("summary", "Σύνοψη");
    el.insert("connections", "Συνδέσεις");
    el.insert("credentials_captured", "Καταγεγραμμένα Διαπιστευτήρια");
    el.insert("files_transferred", "Μεταφερθέντα Αρχεία");
    el.insert("dns_queries", "Ερωτήματα DNS");
    el.insert("http_requests", "Αιτήματα HTTP");
    el.insert("smtp_emails", "Μηνύματα SMTP");
    el.insert("ssh_attempts", "Απόπειρες SSH");
    el.insert("telnet_sessions", "Συνεδρίες Telnet");
    el.insert("start_time", "Ώρα Έναρξης");
    el.insert("end_time", "Ώρα Λήξης");
    el.insert("duration", "Διάρκεια");
    el.insert("node_id", "ID Κόμβου");
    el.insert("region", "Περιοχή");
    el.insert("destination", "Προορισμός");
    m.insert("el", el);

    let mut hu = HashMap::new();
    hu.insert(
        "report_title",
        "NetTrap - Hálózati Viselkedési Mutatók Jelentés",
    );
    hu.insert("total_events", "Összes Esemény");
    hu.insert("unique_sources", "Egyedi Források");
    hu.insert("protocols", "Protokollok");
    hu.insert("protocol_summary", "Protokoll Összefoglalás");
    hu.insert("protocol", "Protokoll");
    hu.insert("events", "Események");
    hu.insert("all_events", "Összes Esemény");
    hu.insert("time", "Idő");
    hu.insert("listener", "Szolgáltatás");
    hu.insert("source", "Forrás");
    hu.insert("port", "Port");
    hu.insert("indicators", "Mutatók");
    hu.insert("process", "Folyamat");
    hu.insert("generated_by", "Jelentést a NetTrap készítette");
    hu.insert("no_events", "Nem rögzítettek eseményeket");
    hu.insert("summary", "Összefoglalás");
    hu.insert("connections", "Kapcsolatok");
    hu.insert("credentials_captured", "Rögzített Hitelesítő Adatok");
    hu.insert("files_transferred", "Átvitt Fájlok");
    hu.insert("dns_queries", "DNS-lekérdezések");
    hu.insert("http_requests", "HTTP-kérések");
    hu.insert("smtp_emails", "SMTP-levelek");
    hu.insert("ssh_attempts", "SSH-kísérletek");
    hu.insert("telnet_sessions", "Telnet-munkamenetek");
    hu.insert("start_time", "Kezdési Idő");
    hu.insert("end_time", "Befejezési Idő");
    hu.insert("duration", "Időtartam");
    hu.insert("node_id", "Csomópont-ID");
    hu.insert("region", "Régió");
    hu.insert("destination", "Cél");
    m.insert("hu", hu);

    let mut cs = HashMap::new();
    cs.insert(
        "report_title",
        "NetTrap - Zpráva o Indikátorech Síťového Chování",
    );
    cs.insert("total_events", "Celkem Událostí");
    cs.insert("unique_sources", "Unikátní Zdroje");
    cs.insert("protocols", "Protokoly");
    cs.insert("protocol_summary", "Shrnutí Protokolů");
    cs.insert("protocol", "Protokol");
    cs.insert("events", "Události");
    cs.insert("all_events", "Všechny Události");
    cs.insert("time", "Čas");
    cs.insert("listener", "Služba");
    cs.insert("source", "Zdroj");
    cs.insert("port", "Port");
    cs.insert("indicators", "Indikátory");
    cs.insert("process", "Proces");
    cs.insert("generated_by", "Zprávu vytvořil NetTrap");
    cs.insert("no_events", "Nebyly zachyceny žádné události");
    cs.insert("summary", "Shrnutí");
    cs.insert("connections", "Spojení");
    cs.insert("credentials_captured", "Zachycené Přihlašovací Údaje");
    cs.insert("files_transferred", "Přenesené Soubory");
    cs.insert("dns_queries", "DNS dotazy");
    cs.insert("http_requests", "HTTP požadavky");
    cs.insert("smtp_emails", "SMTP e-maily");
    cs.insert("ssh_attempts", "SSH pokusy");
    cs.insert("telnet_sessions", "Telnet relace");
    cs.insert("start_time", "Čas Zahájení");
    cs.insert("end_time", "Čas Ukončení");
    cs.insert("duration", "Trvání");
    cs.insert("node_id", "ID Uzlu");
    cs.insert("region", "Region");
    cs.insert("destination", "Cíl");
    m.insert("cs", cs);

    let mut sk = HashMap::new();
    sk.insert(
        "report_title",
        "NetTrap - Správa o Indikátoroch Sieťového Správania",
    );
    sk.insert("total_events", "Celkový Počet Udalostí");
    sk.insert("unique_sources", "Jedinečné Zdroje");
    sk.insert("protocols", "Protokoly");
    sk.insert("protocol_summary", "Zhrnutie Protokolov");
    sk.insert("protocol", "Protokol");
    sk.insert("events", "Udalosti");
    sk.insert("all_events", "Všetky Udalosti");
    sk.insert("time", "Čas");
    sk.insert("listener", "Služba");
    sk.insert("source", "Zdroj");
    sk.insert("port", "Port");
    sk.insert("indicators", "Indikátory");
    sk.insert("process", "Proces");
    sk.insert("generated_by", "Správu vytvoril NetTrap");
    sk.insert("no_events", "Neboli zachytené žiadne udalosti");
    sk.insert("summary", "Zhrnutie");
    sk.insert("connections", "Spojenia");
    sk.insert("dns_queries", "DNS dotazy");
    sk.insert("http_requests", "HTTP požiadavky");
    sk.insert("credentials_captured", "Zachytené poverenia");
    sk.insert("files_transferred", "Prenesené súbory");
    sk.insert("smtp_emails", "SMTP e-maily");
    sk.insert("ssh_attempts", "Pokusy SSH");
    sk.insert("telnet_sessions", "Telnet relácie");
    sk.insert("start_time", "Čas začiatku");
    sk.insert("end_time", "Čas ukončenia");
    sk.insert("duration", "Trvanie");
    sk.insert("node_id", "ID uzla");
    sk.insert("region", "Región");
    sk.insert("destination", "Cieľ");
    m.insert("sk", sk);

    let mut sl = HashMap::new();
    sl.insert(
        "report_title",
        "NetTrap - Poročilo o Kazalnikih Omrežnega Vedenja",
    );
    sl.insert("total_events", "Skupaj Dogodkov");
    sl.insert("unique_sources", "Edinstveni Viri");
    sl.insert("protocols", "Protokoli");
    sl.insert("protocol_summary", "Povzetek Protokolov");
    sl.insert("protocol", "Protokol");
    sl.insert("events", "Dogodki");
    sl.insert("all_events", "Vsi Dogodki");
    sl.insert("time", "Čas");
    sl.insert("listener", "Storitev");
    sl.insert("source", "Vir");
    sl.insert("port", "Vrata");
    sl.insert("indicators", "Kazalniki");
    sl.insert("process", "Proces");
    sl.insert("generated_by", "Poročilo ustvaril NetTrap");
    sl.insert("no_events", "Ni zajetih dogodkov");
    sl.insert("summary", "Povzetek");
    sl.insert("connections", "Povezave");
    sl.insert("dns_queries", "DNS poizvedbe");
    sl.insert("http_requests", "HTTP zahteve");
    sl.insert("credentials_captured", "Zajete poverilnice");
    sl.insert("files_transferred", "Prenesene datoteke");
    sl.insert("smtp_emails", "E-poštna sporočila SMTP");
    sl.insert("ssh_attempts", "Poskusi SSH");
    sl.insert("telnet_sessions", "Telnet seje");
    sl.insert("start_time", "Čas začetka");
    sl.insert("end_time", "Čas konca");
    sl.insert("duration", "Trajanje");
    sl.insert("node_id", "ID vozlišča");
    sl.insert("region", "Regija");
    sl.insert("destination", "Cilj");
    m.insert("sl", sl);

    let mut hr = HashMap::new();
    hr.insert(
        "report_title",
        "NetTrap - Izvješće o Pokazateljima Mrežnog Ponašanja",
    );
    hr.insert("total_events", "Ukupno Događaja");
    hr.insert("unique_sources", "Jedinstveni Izvori");
    hr.insert("protocols", "Protokoli");
    hr.insert("protocol_summary", "Sažetak Protokola");
    hr.insert("protocol", "Protokol");
    hr.insert("events", "Događaji");
    hr.insert("all_events", "Svi Događaji");
    hr.insert("time", "Vrijeme");
    hr.insert("listener", "Usluga");
    hr.insert("source", "Izvor");
    hr.insert("port", "Port");
    hr.insert("indicators", "Pokazatelji");
    hr.insert("process", "Proces");
    hr.insert("generated_by", "Izvješće generirao NetTrap");
    hr.insert("no_events", "Nisu zabilježeni događaji");
    hr.insert("summary", "Sažetak");
    hr.insert("connections", "Veze");
    hr.insert("dns_queries", "DNS upiti");
    hr.insert("http_requests", "HTTP zahtjevi");
    hr.insert("credentials_captured", "Uhvaćene vjerodajnice");
    hr.insert("files_transferred", "Prenesene datoteke");
    hr.insert("smtp_emails", "SMTP e-poruke");
    hr.insert("ssh_attempts", "SSH pokušaji");
    hr.insert("telnet_sessions", "Telnet sesije");
    hr.insert("start_time", "Vrijeme početka");
    hr.insert("end_time", "Vrijeme završetka");
    hr.insert("duration", "Trajanje");
    hr.insert("node_id", "ID čvora");
    hr.insert("region", "Regija");
    hr.insert("destination", "Odredište");
    m.insert("hr", hr);

    let mut bg = HashMap::new();
    bg.insert(
        "report_title",
        "NetTrap - Доклад за Индикатори на Мрежово Поведение",
    );
    bg.insert("total_events", "Общо Събития");
    bg.insert("unique_sources", "Уникални Източници");
    bg.insert("protocols", "Протоколи");
    bg.insert("protocol_summary", "Обобщение на Протоколите");
    bg.insert("protocol", "Протокол");
    bg.insert("events", "Събития");
    bg.insert("all_events", "Всички Събития");
    bg.insert("time", "Време");
    bg.insert("listener", "Услуга");
    bg.insert("source", "Източник");
    bg.insert("port", "Порт");
    bg.insert("indicators", "Индикатори");
    bg.insert("process", "Процес");
    bg.insert("generated_by", "Докладът е създаден от NetTrap");
    bg.insert("no_events", "Няма уловени събития");
    bg.insert("summary", "Резюме");
    bg.insert("connections", "Връзки");
    bg.insert("dns_queries", "DNS заявки");
    bg.insert("http_requests", "HTTP заявки");
    bg.insert("credentials_captured", "Уловени идентификационни данни");
    bg.insert("files_transferred", "Прехвърлени файлове");
    bg.insert("smtp_emails", "SMTP имейли");
    bg.insert("ssh_attempts", "SSH опити");
    bg.insert("telnet_sessions", "Telnet сесии");
    bg.insert("start_time", "Начален час");
    bg.insert("end_time", "Краен час");
    bg.insert("duration", "Продължителност");
    bg.insert("node_id", "ID на възел");
    bg.insert("region", "Регион");
    bg.insert("destination", "Местоназначение");
    m.insert("bg", bg);

    let mut et = HashMap::new();
    et.insert(
        "report_title",
        "NetTrap - Võrgukäitumise Indikaatorite Aruanne",
    );
    et.insert("total_events", "Sündmusi Kokku");
    et.insert("unique_sources", "Unikaalsed Allikad");
    et.insert("protocols", "Protokollid");
    et.insert("protocol_summary", "Protokollide Kokkuvõte");
    et.insert("protocol", "Protokoll");
    et.insert("events", "Sündmused");
    et.insert("all_events", "Kõik Sündmused");
    et.insert("time", "Aeg");
    et.insert("listener", "Teenus");
    et.insert("source", "Allikas");
    et.insert("port", "Port");
    et.insert("indicators", "Indikaatorid");
    et.insert("process", "Protsess");
    et.insert("generated_by", "Aruande koostas NetTrap");
    et.insert("no_events", "Ühtegi sündmust ei jäädvustatud");
    et.insert("summary", "Kokkuvõte");
    et.insert("connections", "Ühendused");
    et.insert("dns_queries", "DNS päringud");
    et.insert("http_requests", "HTTP päringud");
    et.insert("credentials_captured", "Püütud mandaadid");
    et.insert("files_transferred", "Ülekantud failid");
    et.insert("smtp_emails", "SMTP e-kirjad");
    et.insert("ssh_attempts", "SSH katsed");
    et.insert("telnet_sessions", "Telneti seansid");
    et.insert("start_time", "Algusaeg");
    et.insert("end_time", "Lõpuaeg");
    et.insert("duration", "Kestus");
    et.insert("node_id", "Sõlme ID");
    et.insert("region", "Piirkond");
    et.insert("destination", "Sihtkoht");
    m.insert("et", et);

    let mut lv = HashMap::new();
    lv.insert(
        "report_title",
        "NetTrap - Tīkla Uzvedības Indikatoru Pārskats",
    );
    lv.insert("total_events", "Kopējie Notikumi");
    lv.insert("unique_sources", "Unikāli Avoti");
    lv.insert("protocols", "Protokoli");
    lv.insert("protocol_summary", "Protokolu Kopsavilkums");
    lv.insert("protocol", "Protokols");
    lv.insert("events", "Notikumi");
    lv.insert("all_events", "Visi Notikumi");
    lv.insert("time", "Laiks");
    lv.insert("listener", "Pakalpojums");
    lv.insert("source", "Avots");
    lv.insert("port", "Ports");
    lv.insert("indicators", "Indikatori");
    lv.insert("process", "Process");
    lv.insert("generated_by", "Pārskatu izveidoja NetTrap");
    lv.insert("no_events", "Nav notvert neviens notikums");
    lv.insert("summary", "Kopsavilkums");
    lv.insert("connections", "Savienojumi");
    lv.insert("dns_queries", "DNS vaicājumi");
    lv.insert("http_requests", "HTTP pieprasījumi");
    lv.insert("credentials_captured", "Tvertie akreditācijas dati");
    lv.insert("files_transferred", "Pārsūtītie faili");
    lv.insert("smtp_emails", "SMTP e-pasti");
    lv.insert("ssh_attempts", "SSH mēģinājumi");
    lv.insert("telnet_sessions", "Telnet sesijas");
    lv.insert("start_time", "Sākuma laiks");
    lv.insert("end_time", "Beigu laiks");
    lv.insert("duration", "Ilgums");
    lv.insert("node_id", "Mezgla ID");
    lv.insert("region", "Reģions");
    lv.insert("destination", "Galamērķis");
    m.insert("lv", lv);

    let mut lt = HashMap::new();
    lt.insert(
        "report_title",
        "NetTrap - Tinklo Elgesio Rodiklių Ataskaita",
    );
    lt.insert("total_events", "Iš Viso Įvykių");
    lt.insert("unique_sources", "Unikalūs Šaltiniai");
    lt.insert("protocols", "Protokolai");
    lt.insert("protocol_summary", "Protokolų Suvestinė");
    lt.insert("protocol", "Protokolas");
    lt.insert("events", "Įvykiai");
    lt.insert("all_events", "Visi Įvykiai");
    lt.insert("time", "Laikas");
    lt.insert("listener", "Paslauga");
    lt.insert("source", "Šaltinis");
    lt.insert("port", "Prievadas");
    lt.insert("indicators", "Rodikliai");
    lt.insert("process", "Procesas");
    lt.insert("generated_by", "Ataskaitą sukūrė NetTrap");
    lt.insert("no_events", "Nepagauta jokių įvykių");
    lt.insert("summary", "Santrauka");
    lt.insert("connections", "Prisijungimai");
    lt.insert("dns_queries", "DNS užklausos");
    lt.insert("http_requests", "HTTP užklausos");
    lt.insert("credentials_captured", "Užfiksuoti kredencialai");
    lt.insert("files_transferred", "Perkelti failai");
    lt.insert("smtp_emails", "SMTP el. laiškai");
    lt.insert("ssh_attempts", "SSH bandymai");
    lt.insert("telnet_sessions", "Telnet seansai");
    lt.insert("start_time", "Pradžios laikas");
    lt.insert("end_time", "Pabaigos laikas");
    lt.insert("duration", "Trukmė");
    lt.insert("node_id", "Mazgo ID");
    lt.insert("region", "Regionas");
    lt.insert("destination", "Paskirtis");
    m.insert("lt", lt);

    let mut mt = HashMap::new();
    mt.insert(
        "report_title",
        "NetTrap - Rapport dwar Indikaturi ta' Mġiba tan-Netwerk",
    );
    mt.insert("total_events", "Avvenimenti Totali");
    mt.insert("unique_sources", "Sorsi Uniċi");
    mt.insert("protocols", "Protokolli");
    mt.insert("protocol_summary", "Sommarju tal-Protokolli");
    mt.insert("protocol", "Protokoll");
    mt.insert("events", "Avvenimenti");
    mt.insert("all_events", "L-Avvenimenti Kollha");
    mt.insert("time", "Ħin");
    mt.insert("listener", "Servizz");
    mt.insert("source", "Sors");
    mt.insert("port", "Port");
    mt.insert("indicators", "Indikaturi");
    mt.insert("process", "Proċess");
    mt.insert("generated_by", "Rapport iġġenerat minn NetTrap");
    mt.insert("no_events", "L-ebda avveniment inqabad");
    mt.insert("summary", "Sommarju");
    mt.insert("connections", "Konnessjonijiet");
    mt.insert("dns_queries", "Mistoqsijiet DNS");
    mt.insert("http_requests", "Talbiet HTTP");
    mt.insert("credentials_captured", "Kredenzjali maqbuda");
    mt.insert("files_transferred", "Fajls trasferiti");
    mt.insert("smtp_emails", "Emails SMTP");
    mt.insert("ssh_attempts", "Tentattivi SSH");
    mt.insert("telnet_sessions", "Sessjonijiet Telnet");
    mt.insert("start_time", "Ħin tal-bidu");
    mt.insert("end_time", "Ħin tat-tmiem");
    mt.insert("duration", "Tul");
    mt.insert("node_id", "ID tan-nodu");
    mt.insert("region", "Reġjun");
    mt.insert("destination", "Destinazzjoni");
    m.insert("mt", mt);

    let mut ga = HashMap::new();
    ga.insert(
        "report_title",
        "NetTrap - Tuarascáil ar Tháscairí Iompair Líonra",
    );
    ga.insert("total_events", "Imeachtaí Iomlána");
    ga.insert("unique_sources", "Foinsí Uathúla");
    ga.insert("protocols", "Prótacail");
    ga.insert("protocol_summary", "Achoimre ar Phrótacail");
    ga.insert("protocol", "Prótacal");
    ga.insert("events", "Imeachtaí");
    ga.insert("all_events", "Gach Imeacht");
    ga.insert("time", "Am");
    ga.insert("listener", "Seirbhís");
    ga.insert("source", "Foinse");
    ga.insert("port", "Port");
    ga.insert("indicators", "Táscairí");
    ga.insert("process", "Próiseas");
    ga.insert("generated_by", "Tuarascáil ginte ag NetTrap");
    ga.insert("no_events", "Níor gabhadh aon imeacht");
    ga.insert("summary", "Achoimre");
    ga.insert("connections", "Naisc");
    ga.insert("dns_queries", "Fiosrúcháin DNS");
    ga.insert("http_requests", "Iarratais HTTP");
    ga.insert("credentials_captured", "Dintiúir gafa");
    ga.insert("files_transferred", "Comhaid aistrithe");
    ga.insert("smtp_emails", "Ríomhphoist SMTP");
    ga.insert("ssh_attempts", "Iarrachtaí SSH");
    ga.insert("telnet_sessions", "Seisiúin Telnet");
    ga.insert("start_time", "Am tosaigh");
    ga.insert("end_time", "Am críochnaithe");
    ga.insert("duration", "Fad");
    ga.insert("node_id", "Aitheantas nóid");
    ga.insert("region", "Réigiún");
    ga.insert("destination", "Ceann scríbe");
    m.insert("ga", ga);

    let mut eu = HashMap::new();
    eu.insert(
        "report_title",
        "NetTrap - Sareko Jokabide Adierazleen Txostena",
    );
    eu.insert("total_events", "Gertaera Guztira");
    eu.insert("unique_sources", "Iturri Bakarrak");
    eu.insert("protocols", "Protokoloak");
    eu.insert("protocol_summary", "Protokoloen Laburpena");
    eu.insert("protocol", "Protokoloa");
    eu.insert("events", "Gertaerak");
    eu.insert("all_events", "Gertaera Guztiak");
    eu.insert("time", "Ordua");
    eu.insert("listener", "Zerbitzua");
    eu.insert("source", "Iturria");
    eu.insert("port", "Portua");
    eu.insert("indicators", "Adierazleak");
    eu.insert("process", "Prozesua");
    eu.insert("generated_by", "Txostena NetTrap-ek sortu du");
    eu.insert("no_events", "Ez da gertaerarik harrapatu");
    eu.insert("summary", "Laburpena");
    eu.insert("connections", "Konexioak");
    eu.insert("dns_queries", "DNS kontsultak");
    eu.insert("http_requests", "HTTP eskaerak");
    eu.insert("credentials_captured", "Harrapatutako kredentzialak");
    eu.insert("files_transferred", "Transferitutako fitxategiak");
    eu.insert("smtp_emails", "SMTP mezuak");
    eu.insert("ssh_attempts", "SSH saiakerak");
    eu.insert("telnet_sessions", "Telnet saioak");
    eu.insert("start_time", "Hasiera-ordua");
    eu.insert("end_time", "Amaiera-ordua");
    eu.insert("duration", "Iraupena");
    eu.insert("node_id", "Nodoaren IDa");
    eu.insert("region", "Eskualdea");
    eu.insert("destination", "Helmuga");
    m.insert("eu", eu);

    let mut ca = HashMap::new();
    ca.insert(
        "report_title",
        "NetTrap - Informe d'Indicadors de Comportament de Xarxa",
    );
    ca.insert("total_events", "Total d'Esdeveniments");
    ca.insert("unique_sources", "Fonts Úniques");
    ca.insert("protocols", "Protocols");
    ca.insert("protocol_summary", "Resum de Protocols");
    ca.insert("protocol", "Protocol");
    ca.insert("events", "Esdeveniments");
    ca.insert("all_events", "Tots els Esdeveniments");
    ca.insert("time", "Hora");
    ca.insert("listener", "Servei");
    ca.insert("source", "Font");
    ca.insert("port", "Port");
    ca.insert("indicators", "Indicadors");
    ca.insert("process", "Procés");
    ca.insert("generated_by", "Informe generat per NetTrap");
    ca.insert("no_events", "No s'han capturat esdeveniments");
    ca.insert("summary", "Resum");
    ca.insert("connections", "Connexions");
    ca.insert("dns_queries", "Consultes DNS");
    ca.insert("http_requests", "Sol·licituds HTTP");
    ca.insert("credentials_captured", "Credencials capturades");
    ca.insert("files_transferred", "Fitxers transferits");
    ca.insert("smtp_emails", "Correus SMTP");
    ca.insert("ssh_attempts", "Intents SSH");
    ca.insert("telnet_sessions", "Sessions Telnet");
    ca.insert("start_time", "Hora d'inici");
    ca.insert("end_time", "Hora de finalització");
    ca.insert("duration", "Durada");
    ca.insert("node_id", "ID del node");
    ca.insert("region", "Regió");
    ca.insert("destination", "Destinació");
    m.insert("ca", ca);

    let mut zh = HashMap::new();
    zh.insert("report_title", "NetTrap - 网络行为指标报告");
    zh.insert("total_events", "事件总数");
    zh.insert("unique_sources", "唯一来源");
    zh.insert("protocols", "协议");
    zh.insert("protocol_summary", "协议摘要");
    zh.insert("protocol", "协议");
    zh.insert("events", "事件");
    zh.insert("all_events", "所有事件");
    zh.insert("time", "时间");
    zh.insert("listener", "服务");
    zh.insert("source", "来源");
    zh.insert("port", "端口");
    zh.insert("indicators", "指标");
    zh.insert("process", "进程");
    zh.insert("generated_by", "报告由 NetTrap 生成");
    zh.insert("no_events", "未捕获任何事件");
    zh.insert("summary", "摘要");
    zh.insert("connections", "连接");
    zh.insert("credentials_captured", "捕获的凭据");
    zh.insert("files_transferred", "传输的文件");
    zh.insert("dns_queries", "DNS查询");
    zh.insert("http_requests", "HTTP请求");
    zh.insert("smtp_emails", "SMTP邮件");
    zh.insert("ssh_attempts", "SSH尝试");
    zh.insert("telnet_sessions", "Telnet会话");
    zh.insert("start_time", "开始时间");
    zh.insert("end_time", "结束时间");
    zh.insert("duration", "持续时间");
    zh.insert("node_id", "节点ID");
    zh.insert("region", "区域");
    zh.insert("destination", "目标");
    m.insert("zh", zh);

    let mut hi = HashMap::new();
    hi.insert("report_title", "NetTrap - नेटवर्क व्यवहार संकेतक रिपोर्ट");
    hi.insert("total_events", "कुल घटनाएँ");
    hi.insert("unique_sources", "अद्वितीय स्रोत");
    hi.insert("protocols", "प्रोटोकॉल");
    hi.insert("protocol_summary", "प्रोटोकॉल सारांश");
    hi.insert("protocol", "प्रोटोकॉल");
    hi.insert("events", "घटनाएँ");
    hi.insert("all_events", "सभी घटनाएँ");
    hi.insert("time", "समय");
    hi.insert("listener", "सेवा");
    hi.insert("source", "स्रोत");
    hi.insert("port", "पोर्ट");
    hi.insert("indicators", "संकेतक");
    hi.insert("process", "प्रक्रिया");
    hi.insert("generated_by", "NetTrap द्वारा रिपोर्ट जनरेट की गई");
    hi.insert("no_events", "कोई घटना नहीं पकड़ी गई");
    hi.insert("summary", "सारांश");
    hi.insert("connections", "कनेक्शन");
    hi.insert("credentials_captured", "कैप्चर किए गए क्रेडेंशियल");
    hi.insert("files_transferred", "स्थानांतरित फ़ाइलें");
    hi.insert("dns_queries", "DNS प्रश्न");
    hi.insert("http_requests", "HTTP अनुरोध");
    hi.insert("smtp_emails", "SMTP ईमेल");
    hi.insert("ssh_attempts", "SSH प्रयास");
    hi.insert("telnet_sessions", "Telnet सत्र");
    hi.insert("start_time", "प्रारंभ समय");
    hi.insert("end_time", "समाप्ति समय");
    hi.insert("duration", "अवधि");
    hi.insert("node_id", "नोड ID");
    hi.insert("region", "क्षेत्र");
    hi.insert("destination", "गंतव्य");
    m.insert("hi", hi);

    let mut ru = HashMap::new();
    ru.insert(
        "report_title",
        "NetTrap - Отчёт об Индикаторах Сетевого Поведения",
    );
    ru.insert("total_events", "Всего Событий");
    ru.insert("unique_sources", "Уникальные Источники");
    ru.insert("protocols", "Протоколы");
    ru.insert("protocol_summary", "Сводка по Протоколам");
    ru.insert("protocol", "Протокол");
    ru.insert("events", "События");
    ru.insert("all_events", "Все События");
    ru.insert("time", "Время");
    ru.insert("listener", "Сервис");
    ru.insert("source", "Источник");
    ru.insert("port", "Порт");
    ru.insert("indicators", "Индикаторы");
    ru.insert("process", "Процесс");
    ru.insert("generated_by", "Отчёт создан NetTrap");
    ru.insert("no_events", "События не зафиксированы");
    ru.insert("summary", "Итого");
    ru.insert("connections", "Соединения");
    ru.insert("credentials_captured", "Перехваченные Учётные Данные");
    ru.insert("files_transferred", "Переданные Файлы");
    ru.insert("dns_queries", "DNS-запросы");
    ru.insert("http_requests", "HTTP-запросы");
    ru.insert("smtp_emails", "SMTP-письма");
    ru.insert("ssh_attempts", "SSH-попытки");
    ru.insert("telnet_sessions", "Telnet-сессии");
    ru.insert("start_time", "Время Начала");
    ru.insert("end_time", "Время Окончания");
    ru.insert("duration", "Длительность");
    ru.insert("node_id", "ID Узла");
    ru.insert("region", "Регион");
    ru.insert("destination", "Назначение");
    m.insert("ru", ru);

    let mut bn = HashMap::new();
    bn.insert("report_title", "NetTrap - নেটওয়ার্ক আচরণ সূচক প্রতিবেদন");
    bn.insert("total_events", "মোট ঘটনা");
    bn.insert("unique_sources", "অনন্য উৎস");
    bn.insert("protocols", "প্রোটোকল");
    bn.insert("protocol_summary", "প্রোটোকল সারসংক্ষেপ");
    bn.insert("protocol", "প্রোটোকল");
    bn.insert("events", "ঘটনা");
    bn.insert("all_events", "সমস্ত ঘটনা");
    bn.insert("time", "সময়");
    bn.insert("listener", "সেবা");
    bn.insert("source", "উৎস");
    bn.insert("port", "পোর্ট");
    bn.insert("indicators", "সূচক");
    bn.insert("process", "প্রক্রিয়া");
    bn.insert("generated_by", "NetTrap দ্বারা প্রতিবেদন তৈরি");
    bn.insert("no_events", "কোনো ঘটনা ধরা পড়েনি");
    bn.insert("summary", "সারসংক্ষেপ");
    bn.insert("connections", "সংযোগ");
    bn.insert("dns_queries", "DNS প্রশ্ন");
    bn.insert("http_requests", "HTTP অনুরোধ");
    bn.insert("credentials_captured", "ক্যাপচার করা শংসাপত্র");
    bn.insert("files_transferred", "স্থানান্তরিত ফাইল");
    bn.insert("smtp_emails", "SMTP ইমেল");
    bn.insert("ssh_attempts", "SSH প্রচেষ্টা");
    bn.insert("telnet_sessions", "Telnet সেশন");
    bn.insert("start_time", "শুরুর সময়");
    bn.insert("end_time", "শেষের সময়");
    bn.insert("duration", "সময়কাল");
    bn.insert("node_id", "নোড আইডি");
    bn.insert("region", "অঞ্চল");
    bn.insert("destination", "গন্তব্য");
    m.insert("bn", bn);

    let mut ur = HashMap::new();
    ur.insert("report_title", "NetTrap - نیٹ ورک رویے کے اشاریوں کی رپورٹ");
    ur.insert("total_events", "کل واقعات");
    ur.insert("unique_sources", "منفرد ذرائع");
    ur.insert("protocols", "پروٹوکول");
    ur.insert("protocol_summary", "پروٹوکول خلاصہ");
    ur.insert("protocol", "پروٹوکول");
    ur.insert("events", "واقعات");
    ur.insert("all_events", "تمام واقعات");
    ur.insert("time", "وقت");
    ur.insert("listener", "سروس");
    ur.insert("source", "ذریعہ");
    ur.insert("port", "پورٹ");
    ur.insert("indicators", "اشارے");
    ur.insert("process", "عمل");
    ur.insert("generated_by", "رپورٹ NetTrap نے تیار کی");
    ur.insert("no_events", "کوئی واقعہ نہیں پکڑا گیا");
    ur.insert("summary", "خلاصہ");
    ur.insert("connections", "کنکشن");
    ur.insert("dns_queries", "DNS استفسارات");
    ur.insert("http_requests", "HTTP درخواستیں");
    ur.insert("credentials_captured", "حاصل کردہ اسناد");
    ur.insert("files_transferred", "منتقل کردہ فائلیں");
    ur.insert("smtp_emails", "SMTP ای میلز");
    ur.insert("ssh_attempts", "SSH کوششیں");
    ur.insert("telnet_sessions", "Telnet سیشنز");
    ur.insert("start_time", "آغاز کا وقت");
    ur.insert("end_time", "اختتام کا وقت");
    ur.insert("duration", "دورانیہ");
    ur.insert("node_id", "نوڈ آئی ڈی");
    ur.insert("region", "علاقہ");
    ur.insert("destination", "منزل");
    m.insert("ur", ur);

    let mut ar = HashMap::new();
    ar.insert("report_title", "NetTrap - تقرير مؤشرات السلوك الشبكي");
    ar.insert("total_events", "إجمالي الأحداث");
    ar.insert("unique_sources", "المصادر الفريدة");
    ar.insert("protocols", "البروتوكولات");
    ar.insert("protocol_summary", "ملخص البروتوكولات");
    ar.insert("protocol", "البروتوكول");
    ar.insert("events", "الأحداث");
    ar.insert("all_events", "جميع الأحداث");
    ar.insert("time", "الوقت");
    ar.insert("listener", "الخدمة");
    ar.insert("source", "المصدر");
    ar.insert("port", "المنفذ");
    ar.insert("indicators", "المؤشرات");
    ar.insert("process", "العملية");
    ar.insert("generated_by", "تم إنشاء التقرير بواسطة NetTrap");
    ar.insert("no_events", "لم يتم التقاط أي أحداث");
    ar.insert("summary", "ملخص");
    ar.insert("connections", "الاتصالات");
    ar.insert("credentials_captured", "بيانات الاعتماد الملتقطة");
    ar.insert("files_transferred", "الملفات المنقولة");
    ar.insert("dns_queries", "استعلامات DNS");
    ar.insert("http_requests", "طلبات HTTP");
    ar.insert("smtp_emails", "رسائل SMTP");
    ar.insert("ssh_attempts", "محاولات SSH");
    ar.insert("telnet_sessions", "جلسات Telnet");
    ar.insert("start_time", "وقت البدء");
    ar.insert("end_time", "وقت الانتهاء");
    ar.insert("duration", "المدة");
    ar.insert("node_id", "معرّف العقدة");
    ar.insert("region", "المنطقة");
    ar.insert("destination", "الوجهة");
    m.insert("ar", ar);

    m
});
