[package]
name = "nettrap-proto-ldap"
description = "LDAP protocol handler for NetTrap"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
nettrap-core.workspace = true
tracing.workspace = true
async-trait.workspace = true
