[package]
name = "nettrap-policy"
description = "Policy engine for NetTrap"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
nettrap-core.workspace = true
nettrap-flow.workspace = true
thiserror.workspace = true
serde.workspace = true
regex.workspace = true
ipnet.workspace = true
hashbrown.workspace = true
uuid.workspace = true
parking_lot.workspace = true
tracing.workspace = true
tokio.workspace = true
async-trait.workspace = true